apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reeled-ai
  namespace: reeled-ai-production
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/reeled-ai-production/reeled-ai-repo/reeled-ai-app:v2
        env:
        - name: NODE_ENV
          value: "production"
        - name: GEMINI_API_KEY
          value: "AIzaSyB4Zv84FGbknZZ8_h_Pjc6fDdqiRa3txWQ"
        - name: AZURE_OPENAI_API_KEY
          value: "CouXKPtZYfr6N8w5eGCBhtWVCYetGEhnpL3Cr7TjFUPSu1jM9fpYJQQJ99BDACYeBjFXJ3w3AAAAACOGxmRg"
        - name: AZURE_OPENAI_ENDPOINT
          value: "https://johan-m9b2v62z-eastus.cognitiveservices.azure.com/"
        - name: AZURE_OPENAI_API_VERSION
          value: "2025-01-01-preview"
        - name: AZURE_DALLE_ENDPOINT
          value: "https://johan-m9b2v62z-eastus.cognitiveservices.azure.com/"
        - name: AZURE_DALLE_API_KEY
          value: "CouXKPtZYfr6N8w5eGCBhtWVCYetGEhnpL3Cr7TjFUPSu1jM9fpYJQQJ99BDACYeBjFXJ3w3AAAAACOGxmRg"
        - name: AZURE_GPT4O_DEPLOYMENT
          value: "gpt-4o-reeled"
        - name: AZURE_GPT4_DEPLOYMENT
          value: "gpt-4-reeled"
        - name: AZURE_GPT35_TURBO_DEPLOYMENT
          value: "gpt-35-turbo-reeled"
        - name: AZURE_GPT45_PREVIEW_DEPLOYMENT
          value: "gpt-4.5-preview"
        - name: AZURE_DALLE_DEPLOYMENT
          value: "dall-e-3"
        - name: AZURE_GPT45_API_KEY
          value: "FKp0kcV49TA4XVdpoyQ9zO0vluUAWQNSqqA76dvVvztBi0a13vh7JQQJ99BDACHYHv6XJ3w3AAABACOGqNKj"
        - name: AZURE_GPT45_ENDPOINT
          value: "https://reeled-ai-alpha.openai.azure.com/"
        - name: AZURE_GPT45_API_VERSION
          value: "2025-01-01-preview"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi 